// <auto-generated />
using DB_Table;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Program_Main_.Migrations
{
    [DbContext(typeof(DB_Lasers))]
    [Migration("20231206150654_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DB_Table.Laser", b =>
                {
                    b.Property<int>("LaserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConsumedEnergy")
                        .HasColumnType("TEXT");

                    b.Property<string>("LaserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaximumPower")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximumWeldingDuration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfTriggeredWelds")
                        .HasColumnType("INTEGER");

                    b.HasKey("LaserID");

                    b.ToTable("Lasers");
                });
#pragma warning restore 612, 618
        }
    }
}
